if(NOT OpenCV_DIR AND DEFINED ENV{OpenCV_DIR} AND NOT "$ENV{OpenCV_DIR}" STREQUAL "")
  set(OpenCV_DIR "$ENV{OpenCV_DIR}" CACHE PATH "Path to OpenCVConfig.cmake")
endif()

if(NOT OpenCV_DIR AND DEFINED ENV{ORB_SLAM3_OPENCV_ROOT} AND NOT "$ENV{ORB_SLAM3_OPENCV_ROOT}" STREQUAL "")
  list(PREPEND ORB_SLAM3_OPENCV_HINT_ROOTS "$ENV{ORB_SLAM3_OPENCV_ROOT}")
endif()

if(NOT OpenCV_DIR)
  foreach(_orb_slam3_opencv_root IN LISTS ORB_SLAM3_OPENCV_HINT_ROOTS)
    if(NOT _orb_slam3_opencv_root)
      continue()
    endif()

    if(EXISTS "${_orb_slam3_opencv_root}/OpenCVConfig.cmake")
      set(OpenCV_DIR "${_orb_slam3_opencv_root}" CACHE PATH "Path to OpenCVConfig.cmake")
      break()
    endif()

    file(GLOB_RECURSE _orb_slam3_opencv_configs "${_orb_slam3_opencv_root}/OpenCVConfig.cmake")
    list(LENGTH _orb_slam3_opencv_configs _orb_slam3_opencv_config_count)
    if(_orb_slam3_opencv_config_count GREATER 0)
      list(GET _orb_slam3_opencv_configs 0 _orb_slam3_opencv_config)
      get_filename_component(_orb_slam3_opencv_config_dir "${_orb_slam3_opencv_config}" DIRECTORY)
      set(OpenCV_DIR "${_orb_slam3_opencv_config_dir}" CACHE PATH "Path to OpenCVConfig.cmake")
      break()
    endif()
  endforeach()
endif()

unset(_orb_slam3_opencv_root)
unset(_orb_slam3_opencv_configs)
unset(_orb_slam3_opencv_config)
unset(_orb_slam3_opencv_config_count)
unset(_orb_slam3_opencv_config_dir)
